JUnit version 3.8.2
......E.E.E.E.E
Time: 3.029
There were 5 failures:
1) test6(org.apache.commons.jxpath.ri.axes.UnionContext_ESTest)
java.lang.NullPointerException
	at org.apache.commons.jxpath.ri.axes.UnionContext.setPosition(UnionContext.java:52)
	at org.apache.commons.jxpath.ri.axes.UnionContext_ESTest.test6(UnionContext_ESTest.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
2) test5(org.apache.commons.jxpath.ri.axes.UnionContext_ESTest)
java.lang.NullPointerException
	at org.apache.commons.jxpath.ri.compiler.Path.buildContextChain(Path.java:231)
	at org.apache.commons.jxpath.ri.compiler.Path.evalSteps(Path.java:216)
	at org.apache.commons.jxpath.ri.compiler.ExpressionPath.expressionPath(ExpressionPath.java:183)
	at org.apache.commons.jxpath.ri.compiler.ExpressionPath.compute(ExpressionPath.java:126)
	at org.apache.commons.jxpath.ri.compiler.CoreOperationRelationalExpression.computeValue(CoreOperationRelationalExpression.java:42)
	at org.apache.commons.jxpath.ri.axes.PredicateContext.nextNode(PredicateContext.java:82)
	at org.apache.commons.jxpath.ri.axes.UnionContext.setPosition(UnionContext.java:53)
	at org.apache.commons.jxpath.ri.axes.NodeSetContext.getCurrentNodePointer(NodeSetContext.java:44)
	at org.apache.commons.jxpath.ri.axes.UnionContext_ESTest.test5(UnionContext_ESTest.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
3) test4(org.apache.commons.jxpath.ri.axes.UnionContext_ESTest)
java.lang.NullPointerException
	at org.apache.commons.jxpath.ri.axes.UnionContext.getDocumentOrder(UnionContext.java:42)
	at org.apache.commons.jxpath.ri.axes.UnionContext_ESTest.test4(UnionContext_ESTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
4) test3(org.apache.commons.jxpath.ri.axes.UnionContext_ESTest)
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
	at org.apache.commons.jxpath.ri.axes.NodeSetContext.getCurrentNodePointer(NodeSetContext.java:48)
	at org.apache.commons.jxpath.ri.axes.ChildContext.prepare(ChildContext.java:106)
	at org.apache.commons.jxpath.ri.axes.ChildContext.setPosition(ChildContext.java:97)
	at org.apache.commons.jxpath.ri.axes.ChildContext.nextNode(ChildContext.java:85)
	at org.apache.commons.jxpath.ri.EvalContext.nextSet(EvalContext.java:319)
	at org.apache.commons.jxpath.ri.axes.UnionContext.setPosition(UnionContext.java:52)
	at org.apache.commons.jxpath.ri.axes.UnionContext_ESTest.test3(UnionContext_ESTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
5) test2(org.apache.commons.jxpath.ri.axes.UnionContext_ESTest)
java.lang.UnsupportedOperationException
	at org.apache.commons.jxpath.ri.axes.RootContext.nextSet(RootContext.java:82)
	at org.apache.commons.jxpath.ri.axes.UnionContext.setPosition(UnionContext.java:52)
	at org.apache.commons.jxpath.ri.axes.UnionContext_ESTest.test2(UnionContext_ESTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

FAILURES!!!
Tests run: 10,  Failures: 5

